# Turn on logging, and set ZMK logging to debug output
# CONFIG_ZMK_USB_LOGGING=n
#
# Copyright (c) 2022 Darryl deHaan
# SPDX-License-Identifier: MIT
#

# Enable 32kHz crystal
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y

# SLEEP
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# RGB UNDERGLOW
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_EXT=y
CONFIG_ZMK_RGB_EXT_EXT_POWER=y
CONFIG_ZMK_RGB_EXT_ON_START=n
CONFIG_ZMK_RGB_EXT_BRT_START=50
CONFIG_ZMK_RGB_EXT_BRT_MAX=60
CONFIG_ZMK_RGB_EXT_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_EXT_AUTO_OFF_USB=y
CONFIG_ZMK_RGB_EXT_HUE_START=160
CONFIG_ZMK_RGB_EXT_EFF_START=0

CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=160
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0

# BACKLIGHT
CONFIG_ZMK_BACKLIGHT=n

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#EXT POWER
CONFIG_ZMK_EXT_POWER=y

# MOUSE
CONFIG_ZMK_POINTING=y

# MISC
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8

# SOFT OFF
CONFIG_ZMK_PM_SOFT_OFF=y
