manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: sofle_v2
      url: https://github.com/zael99/zmk-sofle
      revision: main
    - name: bt_rgb
      url: https://github.com/zael99/zmk-bluetooth-rgb
      revision: main
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
  self:
    path: boards
