manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zael99
  projects:
    - name: zmk-sofle
      remote: zmkfirmware
      revision: main
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
  self:
    path: boards
